### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by meeeller** [Ladvien/vscode-looker#4]
How do you us this?  I usually install extensions via sidebar, or .vscd extentions.

Would like to use, but unsure of how...

**Comment by ms32035** [comment]
@meeeller I compiled a pre-release vsix
https://github.com/ms32035/vscode-looker/releases/tag/v0.0.3

**Comment by Ladvien** [comment]
Thank you, @ms32035.  Unfortunately, I don't have the time to push forward on this project unless interest picks up.  And sadly, the current repo is not in a useful state.  I've updated the README with an explanation.

Apologies for the confusion @meeeller.

--Thomas
